name: Build macOS Disk Image with Pyinstaller tool

on:
  push:
    branches:
      - main  # Change to your default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller

    - name: Build the application
      run: |
        pyinstaller --onefile --windowed hello_world.py  # Replace with your script

    - name: Create DMG
      run: |
        mkdir output
        hdiutil create -volname "HelloWorld" -srcfolder dist/hello_world.app -ov -format UDZO output/HelloWorld.dmg

    - name: Upload DMG
      uses: actions/upload-artifact@v3  # Updated to the latest version
      with:
        name: HelloWorld-DMG
        path: output/HelloWorld.dmg
